name: "Text"

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    type: [ opened ]
  
  
jobs: 
  test:
    runs-on: ubuntu-latest
    steps:
    - name: 是否安裝python
    - run: python --version